// frontend/src/app/pages/create-question.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { ApiService } from '../services/api.service';
import { AuthService } from '../services/auth.service';
import { User } from '../models/models';

interface QuestionOption {
  key: string;
  value: string;
}

@Component({
  selector: 'app-create-question',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './create-question.component.html',
  styleUrls: ['./create-question.component.css']
})
export class CreateQuestionComponent implements OnInit {
  user: User | null = null;
  
  // Form fields
  title = '';
  content = '';
  type: string = 'SINGLE_CHOICE';
  difficulty: string = 'MEDIUM';
  answer = '';
  explanation = '';
  tags = '';
  
  // Options for choice questions
  options: QuestionOption[] = [
    { key: 'A', value: '' },
    { key: 'B', value: '' },
    { key: 'C', value: '' },
    { key: 'D', value: '' }
  ];
  
  // UI state
  error = '';
  success = '';
  submitting = false;
  
  // Question types
  questionTypes = [
    { value: 'SINGLE_CHOICE', label: '单选题' },
    { value: 'MULTIPLE_CHOICE', label: '多选题' },
    { value: 'TRUE_FALSE', label: '判断题' },
    { value: 'FILL_BLANK', label: '填空题' },
    { value: 'SHORT_ANSWER', label: '简答题' },
    { value: 'ESSAY', label: '概述题' }
  ];
  
  // Difficulty levels
  difficultyLevels = [
    { value: 'EASY', label: '简单' },
    { value: 'MEDIUM', label: '中等' },
    { value: 'HARD', label: '困难' }
  ];

  constructor(
    private apiService: ApiService,
    private authService: AuthService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.authService.user$.subscribe(user => {
      this.user = user;
      if (!user) {
        this.router.navigate(['/login']);
      }
    });
  }

  get isChoiceQuestion(): boolean {
    return this.type === 'SINGLE_CHOICE' || this.type === 'MULTIPLE_CHOICE';
  }

  get isTrueFalseQuestion(): boolean {
    return this.type === 'TRUE_FALSE';
  }

  addOption(): void {
    const nextKey = String.fromCharCode(65 + this.options.length); // A=65
    this.options.push({ key: nextKey, value: '' });
  }

  removeOption(index: number): void {
    if (this.options.length > 2) {
      this.options.splice(index, 1);
      // Re-assign keys
      this.options.forEach((opt, idx) => {
        opt.key = String.fromCharCode(65 + idx);
      });
    }
  }

  handleSubmit(): void {
    this.error = '';
    this.success = '';

    // Validation
    if (!this.title.trim()) {
      this.error = '请输入题目标题';
      return;
    }

    if (!this.content.trim()) {
      this.error = '请输入题目内容';
      return;
    }

    if (!this.answer.trim()) {
      this.error = '请输入答案';
      return;
    }

    if (this.isChoiceQuestion) {
      const hasEmptyOption = this.options.some(opt => !opt.value.trim());
      if (hasEmptyOption) {
        this.error = '请填写所有选项内容';
        return;
      }
    }

    if (!this.user) {
      this.error = '请先登录';
      return;
    }

    this.submitting = true;

    // Prepare request data
    const requestData: any = {
      title: this.title.trim(),
      content: this.content.trim(),
      type: this.type,
      difficulty: this.difficulty,
      answer: this.answer.trim(),
      explanation: this.explanation.trim(),
      tags: this.tags.trim()
    };

    // Add options for choice questions
    if (this.isChoiceQuestion || this.isTrueFalseQuestion) {
      const optionsObj: any = {};
      if (this.isTrueFalseQuestion) {
        optionsObj['A'] = '正确';
        optionsObj['B'] = '错误';
      } else {
        this.options.forEach(opt => {
          if (opt.value.trim()) {
            optionsObj[opt.key] = opt.value.trim();
          }
        });
      }
      requestData.options = JSON.stringify(optionsObj);
    }

    // Call API
    this.apiService.createQuestion(requestData, this.user.id).subscribe({
      next: (response) => {
        this.submitting = false;
        if (response.success) {
          this.success = '题目创建成功！正在跳转...';
          setTimeout(() => {
            this.router.navigate(['/questions', response.data.id]);
          }, 1500);
        } else {
          this.error = response.message || '创建失败';
        }
      },
      error: (err) => {
        this.submitting = false;
        this.error = err.error?.message || '创建失败，请重试';
      }
    });
  }

  resetForm(): void {
    this.title = '';
    this.content = '';
    this.type = 'SINGLE_CHOICE';
    this.difficulty = 'MEDIUM';
    this.answer = '';
    this.explanation = '';
    this.tags = '';
    this.options = [
      { key: 'A', value: '' },
      { key: 'B', value: '' },
      { key: 'C', value: '' },
      { key: 'D', value: '' }
    ];
    this.error = '';
    this.success = '';
  }
}

<div class="create-question-container">
  <div class="header">
    <h1>创建题目</h1>
    <a routerLink="/" class="back-link">← 返回首页</a>
  </div>

  <div *ngIf="error" class="alert alert-error">{{ error }}</div>
  <div *ngIf="success" class="alert alert-success">{{ success }}</div>

  <form (ngSubmit)="handleSubmit()" class="question-form">
    <!-- 题目标题 -->
    <div class="form-group">
      <label for="title">题目标题 <span class="required">*</span></label>
      <input
        id="title"
        type="text"
        [(ngModel)]="title"
        name="title"
        placeholder="请输入题目标题"
        required
        [disabled]="submitting"
      />
    </div>

    <!-- 题目类型 -->
    <div class="form-group">
      <label for="type">题目类型 <span class="required">*</span></label>
      <select
        id="type"
        [(ngModel)]="type"
        name="type"
        required
        [disabled]="submitting"
      >
        <option *ngFor="let qt of questionTypes" [value]="qt.value">
          {{ qt.label }}
        </option>
      </select>
    </div>

    <!-- 难度 -->
    <div class="form-group">
      <label for="difficulty">难度 <span class="required">*</span></label>
      <select
        id="difficulty"
        [(ngModel)]="difficulty"
        name="difficulty"
        required
        [disabled]="submitting"
      >
        <option *ngFor="let dl of difficultyLevels" [value]="dl.value">
          {{ dl.label }}
        </option>
      </select>
    </div>

    <!-- 题目内容 -->
    <div class="form-group">
      <label for="content">题目内容 <span class="required">*</span></label>
      <textarea
        id="content"
        [(ngModel)]="content"
        name="content"
        rows="6"
        placeholder="请输入题目内容（支持Markdown格式）"
        required
        [disabled]="submitting"
      ></textarea>
      <small class="help-text">支持Markdown格式，如 **粗体** 、*斜体* 、`代码` 等</small>
    </div>

    <!-- 选项（单选、多选题） -->
    <div *ngIf="isChoiceQuestion" class="form-group">
      <label>选项 <span class="required">*</span></label>
      <div class="options-container">
        <div *ngFor="let option of options; let i = index" class="option-row">
          <span class="option-key">{{ option.key }}.</span>
          <input
            type="text"
            [(ngModel)]="option.value"
            [name]="'option-' + i"
            placeholder="请输入选项内容"
            required
            [disabled]="submitting"
          />
          <button
            type="button"
            class="btn-remove"
            (click)="removeOption(i)"
            [disabled]="options.length <= 2 || submitting"
            title="删除选项"
          >
            ✕
          </button>
        </div>
        <button
          type="button"
          class="btn-add-option"
          (click)="addOption()"
          [disabled]="options.length >= 10 || submitting"
        >
          + 添加选项
        </button>
      </div>
    </div>

    <!-- 判断题提示 -->
    <div *ngIf="isTrueFalseQuestion" class="form-group">
      <div class="info-box">
        <strong>判断题选项：</strong> A. 正确 / B. 错误
      </div>
    </div>

    <!-- 答案 -->
    <div class="form-group">
      <label for="answer">答案 <span class="required">*</span></label>
      <div *ngIf="type === 'SINGLE_CHOICE'" class="answer-hint">
        <small>单选题答案格式：输入选项字母，如：A</small>
      </div>
      <div *ngIf="type === 'MULTIPLE_CHOICE'" class="answer-hint">
        <small>多选题答案格式：输入选项字母，用逗号分隔，如：A,C,D</small>
      </div>
      <div *ngIf="type === 'TRUE_FALSE'" class="answer-hint">
        <small>判断题答案格式：A（正确）或 B（错误）</small>
      </div>
      <input
        *ngIf="type !== 'SHORT_ANSWER' && type !== 'ESSAY'"
        id="answer"
        type="text"
        [(ngModel)]="answer"
        name="answer"
        placeholder="请输入答案"
        required
        [disabled]="submitting"
      />
      <textarea
        *ngIf="type === 'SHORT_ANSWER' || type === 'ESSAY'"
        id="answer"
        [(ngModel)]="answer"
        name="answer"
        rows="4"
        placeholder="请输入答案"
        required
        [disabled]="submitting"
      ></textarea>
    </div>

    <!-- 解析 -->
    <div class="form-group">
      <label for="explanation">答案解析</label>
      <textarea
        id="explanation"
        [(ngModel)]="explanation"
        name="explanation"
        rows="4"
        placeholder="请输入答案解析（可选，支持Markdown格式）"
        [disabled]="submitting"
      ></textarea>
      <small class="help-text">为学生提供详细的答案解析</small>
    </div>

    <!-- 标签 -->
    <div class="form-group">
      <label for="tags">标签</label>
      <input
        id="tags"
        type="text"
        [(ngModel)]="tags"
        name="tags"
        placeholder="请输入标签，用逗号分隔，如：数学,代数,函数"
        [disabled]="submitting"
      />
      <small class="help-text">用逗号分隔多个标签，便于分类和搜索</small>
    </div>

    <!-- 提交按钮 -->
    <div class="form-actions">
      <button type="submit" class="btn btn-primary" [disabled]="submitting">
        {{ submitting ? '创建中...' : '创建题目' }}
      </button>
      <button type="button" class="btn btn-secondary" (click)="resetForm()" [disabled]="submitting">
        重置
      </button>
      <a routerLink="/" class="btn btn-link">取消</a>
    </div>
  </form>
</div>

// frontend-react-backup/src/pages/CreateQuestion.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { questionAPI } from '../api';
import { useAuth } from '../AuthContext';

const CreateQuestion: React.FC = () => {
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [type, setType] = useState('SINGLE_CHOICE');
  const [options, setOptions] = useState('');
  const [answer, setAnswer] = useState('');
  const [explanation, setExplanation] = useState('');
  const [difficulty, setDifficulty] = useState('MEDIUM');
  const [tags, setTags] = useState('');
  const { user } = useAuth();
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!user) {
      alert('请先登录');
      navigate('/login');
      return;
    }

    try {
      const response = await questionAPI.create({
        title,
        content,
        type,
        options,
        answer,
        explanation,
        difficulty,
        tags
      }, user.id);

      if (response.data.success) {
        alert('创建成功！');
        navigate('/');
      }
    } catch (error: any) {
      alert(error.response?.data?.message || '创建失败');
    }
  };

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '20px' }}>
      <h2>创建题目</h2>
      <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
        <div>
          <label>题目标题:</label>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            required
            style={{ width: '100%', padding: '8px', marginTop: '5px' }}
          />
        </div>

        <div>
          <label>题目内容:</label>
          <textarea
            value={content}
            onChange={(e) => setContent(e.target.value)}
            required
            style={{ width: '100%', minHeight: '100px', padding: '8px', marginTop: '5px' }}
          />
        </div>

        <div>
          <label>题目类型:</label>
          <select value={type} onChange={(e) => setType(e.target.value)} style={{ width: '100%', padding: '8px', marginTop: '5px' }}>
            <option value="SINGLE_CHOICE">单选题</option>
            <option value="MULTIPLE_CHOICE">多选题</option>
            <option value="TRUE_FALSE">判断题</option>
            <option value="FILL_BLANK">填空题</option>
            <option value="SHORT_ANSWER">简答题</option>
            <option value="ESSAY">概述题 (支持Markdown、Mermaid、LaTeX)</option>
          </select>
        </div>

        <div>
          <label>选项 (JSON格式，如: {`{"A":"选项A","B":"选项B"}`}):</label>
          <textarea
            value={options}
            onChange={(e) => setOptions(e.target.value)}
            placeholder='{"A":"选项A","B":"选项B","C":"选项C","D":"选项D"}'
            style={{ width: '100%', minHeight: '80px', padding: '8px', marginTop: '5px' }}
          />
        </div>

        <div>
          <label>正确答案:</label>
          <input
            type="text"
            value={answer}
            onChange={(e) => setAnswer(e.target.value)}
            required
            style={{ width: '100%', padding: '8px', marginTop: '5px' }}
          />
        </div>

        <div>
          <label>答案解析:</label>
          <textarea
            value={explanation}
            onChange={(e) => setExplanation(e.target.value)}
            style={{ width: '100%', minHeight: '80px', padding: '8px', marginTop: '5px' }}
          />
        </div>

        <div>
          <label>难度:</label>
          <select value={difficulty} onChange={(e) => setDifficulty(e.target.value)} style={{ width: '100%', padding: '8px', marginTop: '5px' }}>
            <option value="EASY">简单</option>
            <option value="MEDIUM">中等</option>
            <option value="HARD">困难</option>
          </select>
        </div>

        <div>
          <label>标签 (逗号分隔):</label>
          <input
            type="text"
            value={tags}
            onChange={(e) => setTags(e.target.value)}
            placeholder="数学,代数,线性方程"
            style={{ width: '100%', padding: '8px', marginTop: '5px' }}
          />
        </div>

        <div style={{ display: 'flex', gap: '10px' }}>
          <button type="submit" style={{ padding: '10px 20px', cursor: 'pointer', background: '#28a745', color: 'white', border: 'none', borderRadius: '5px' }}>
            创建题目
          </button>
          <button type="button" onClick={() => navigate('/')} style={{ padding: '10px 20px', cursor: 'pointer', background: '#6c757d', color: 'white', border: 'none', borderRadius: '5px' }}>
            取消
          </button>
        </div>
      </form>
    </div>
  );
};

export default CreateQuestion;
