// frontend/src/app/pages/login.component.ts
import { Component } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { ApiService } from '../services/api.service';
import { AuthService } from '../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  username = '';
  password = '';
  error = '';

  constructor(
    private apiService: ApiService,
    private authService: AuthService,
    private router: Router
  ) {}

  handleSubmit(): void {
    this.error = '';

    this.apiService.login({ username: this.username, password: this.password }).subscribe({
      next: (response) => {
        if (response.success) {
          this.authService.login(response.data);
          this.router.navigate(['/']);
        } else {
          this.error = response.message;
        }
      },
      error: (err) => {
        this.error = err.error?.message || '登录失败，请重试';
      }
    });
  }
}

<div style="max-width: 400px; margin: 50px auto; padding: 20px;">
  <h2>登录</h2>
  <div *ngIf="error" style="color: red; margin-bottom: 10px;">{{ error }}</div>
  <form (ngSubmit)="handleSubmit()">
    <div style="margin-bottom: 15px;">
      <label>用户名:</label>
      <input
        type="text"
        [(ngModel)]="username"
        name="username"
        required
        style="width: 100%; padding: 8px; margin-top: 5px;"
      />
    </div>
    <div style="margin-bottom: 15px;">
      <label>密码:</label>
      <input
        type="password"
        [(ngModel)]="password"
        name="password"
        required
        style="width: 100%; padding: 8px; margin-top: 5px;"
      />
    </div>
    <button type="submit" style="padding: 10px 20px; cursor: pointer;">
      登录
    </button>
    <div style="margin-top: 15px;">
      没有账号？<a routerLink="/register">注册</a>
    </div>
  </form>
</div>

// frontend-react-backup/src/pages/Login.tsx
import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { authAPI } from '../api';
import { useAuth } from '../AuthContext';

const Login: React.FC = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const navigate = useNavigate();
  const { login } = useAuth();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    try {
      const response = await authAPI.login({ username, password });
      if (response.data.success) {
        login(response.data.data);
        navigate('/');
      } else {
        setError(response.data.message);
      }
    } catch (err: any) {
      setError(err.response?.data?.message || '登录失败，请重试');
    }
  };

  return (
    <div style={{ maxWidth: '400px', margin: '50px auto', padding: '20px' }}>
      <h2>登录</h2>
      {error && <div style={{ color: 'red', marginBottom: '10px' }}>{error}</div>}
      <form onSubmit={handleSubmit}>
        <div style={{ marginBottom: '15px' }}>
          <label>用户名:</label>
          <input
            type="text"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            required
            style={{ width: '100%', padding: '8px', marginTop: '5px' }}
          />
        </div>
        <div style={{ marginBottom: '15px' }}>
          <label>密码:</label>
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            style={{ width: '100%', padding: '8px', marginTop: '5px' }}
          />
        </div>
        <button type="submit" style={{ padding: '10px 20px', cursor: 'pointer' }}>
          登录
        </button>
        <div style={{ marginTop: '15px' }}>
          没有账号？<Link to="/register">注册</Link>
        </div>
      </form>
    </div>
  );
};

export default Login;
