// frontend/src/app/pages/question-detail.component.ts
import {ChangeDetectorRef, Component, OnInit} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { ApiService } from '../services/api.service';
import { AuthService } from '../services/auth.service';
import { Question, User } from '../models/models';
import { MarkdownRendererComponent } from '../components/markdown-renderer.component';

@Component({
  selector: 'app-question-detail',
  standalone: true,
  imports: [CommonModule, FormsModule, MarkdownRendererComponent],
  templateUrl: './question-detail.component.html',
  styleUrls: ['./question-detail.component.css']
})
export class QuestionDetailComponent implements OnInit {
  question: Question | null = null;
  user: User | null = null;
  userAnswer = '';
  selectedOptions: string[] = [];
  submitted = false;
  isCorrect = false;
  score = 0;
  loading = true;
  isCollected = false;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private apiService: ApiService,
    private authService: AuthService,
    private  changeDetector: ChangeDetectorRef
  ) {}

  ngOnInit(): void {
    this.authService.user$.subscribe(user => {
      this.user = user;
    });

    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.loadQuestion(+id);
    }
  }

  loadQuestion(id: number): void {
    this.loading = true;
    this.apiService.getQuestionById(id).subscribe({
      next: (response) => {
        if (response.success) {
          this.question = response.data;
          this.checkIfCollected();
        }
        this.loading = false;
        this.changeDetector.markForCheck();
      },
      error: (error) => {
        console.error('Failed to load question:', error);
        this.loading = false;
        this.changeDetector.markForCheck();
      }
    });
  }

  checkIfCollected(): void {
    if (this.user && this.question) {
      this.apiService.isCollected(this.user.id, this.question.id).subscribe({
        next: (response) => {
          if (response.success) {
            this.isCollected = response.data;
          }
        },
        error: (error) => {
          console.error('Failed to check collection status:', error);
        }
      });
    }
  }

  getOptions(): any[] {
    if (!this.question?.options) return [];
    try {
      const parsed = JSON.parse(this.question.options);
      
      // If parsed is an array, return it as-is
      if (Array.isArray(parsed)) {
        return parsed;
      }
      
      // If parsed is an object, convert it to array format
      if (typeof parsed === 'object' && parsed !== null) {
        return Object.entries(parsed).map(([key, value]) => ({
          key: key,
          value: value
        }));
      }
      
      return [];
    } catch {
      return [];
    }
  }

  toggleOption(optionKey: string): void {
    const index = this.selectedOptions.indexOf(optionKey);
    if (index === -1) {
      if (this.question?.type === 'SINGLE_CHOICE') {
        this.selectedOptions = [optionKey];
      } else {
        this.selectedOptions.push(optionKey);
      }
    } else {
      this.selectedOptions.splice(index, 1);
    }
  }

  submitAnswer(): void {
    if (!this.user || !this.question) return;

    let answer = this.userAnswer;
    if (this.question.type === 'SINGLE_CHOICE' || this.question.type === 'TRUE_FALSE') {
      answer = this.selectedOptions[0] || '';
    } else if (this.question.type === 'MULTIPLE_CHOICE') {
      answer = this.selectedOptions.sort().join(',');
    }

    this.apiService.submitAnswer({
      questionId: this.question.id,
      answer: answer,
      timeSpent: 0
    }, this.user.id).subscribe({
      next: (response) => {
        if (response.success) {
          this.submitted = true;
          this.isCorrect = response.data.isCorrect;
          this.score = response.data.score;
        }
      },
      error: (error) => {
        console.error('Failed to submit answer:', error);
        alert('提交失败');
      }
    });
  }

  toggleCollection(): void {
    if (!this.user || !this.question) return;

    if (this.isCollected) {
      // Remove from collection - we need collection ID
      // For simplicity, we'll just show a message
      alert('取消收藏功能需要从收藏列表中操作');
    } else {
      this.apiService.addCollection(this.question.id, undefined, this.user.id).subscribe({
        next: (response) => {
          if (response.success) {
            this.isCollected = true;
            alert('收藏成功！');
          }
        },
        error: (error) => {
          console.error('Failed to add collection:', error);
          alert('收藏失败');
        }
      });
    }
  }

  getQuestionTypeLabel(type: string): string {
    const types: Record<string, string> = {
      SINGLE_CHOICE: '单选题',
      MULTIPLE_CHOICE: '多选题',
      TRUE_FALSE: '判断题',
      FILL_BLANK: '填空题',
      SHORT_ANSWER: '简答题',
      ESSAY: '概述题',
    };
    return types[type] || type;
  }

  getDifficultyLabel(difficulty: string): string {
    const levels: Record<string, string> = {
      EASY: '简单',
      MEDIUM: '中等',
      HARD: '困难',
    };
    return levels[difficulty] || difficulty;
  }

  isChoiceQuestion(): boolean {
    return this.question?.type === 'SINGLE_CHOICE' || 
           this.question?.type === 'MULTIPLE_CHOICE' || 
           this.question?.type === 'TRUE_FALSE';
  }
}


<div class="question-detail-container">
  <div *ngIf="loading" class="loading">加载中...</div>

  <div *ngIf="!loading && question" class="question-content">
    <div class="question-header">
      <h1>{{ question.title }}</h1>
      <div class="question-meta">
        <span class="badge badge-type">{{ getQuestionTypeLabel(question.type) }}</span>
        <span class="badge badge-difficulty">{{ getDifficultyLabel(question.difficulty) }}</span>
        <button class="btn-collection" (click)="toggleCollection()" *ngIf="user">
          {{ isCollected ? '已收藏 ★' : '收藏 ☆' }}
        </button>
      </div>
    </div>

    <div class="question-body">
      <h3>题目内容:</h3>
      <app-markdown-renderer [content]="question.content"></app-markdown-renderer>

      <!-- 单选题 -->
      <div *ngIf="question.type === 'SINGLE_CHOICE'" class="options-section">
        <h3>选项:</h3>
        <div class="options">
          <div *ngFor="let option of getOptions()" 
               class="option-item" 
               [class.selected]="selectedOptions.includes(option.key)">
            <label>
              <input 
                type="radio" 
                [name]="'option'" 
                [value]="option.key"
                [checked]="selectedOptions.includes(option.key)"
                (change)="toggleOption(option.key)"
                [disabled]="submitted">
              <span class="option-key">{{ option.key }}.</span>
              <span class="option-text">
                <app-markdown-renderer [content]="option.value"></app-markdown-renderer>
              </span>
            </label>
          </div>
        </div>
      </div>

      <!-- 多选题 -->
      <div *ngIf="question.type === 'MULTIPLE_CHOICE'" class="options-section">
        <h3>选项: (可多选)</h3>
        <div class="options">
          <div *ngFor="let option of getOptions()" 
               class="option-item"
               [class.selected]="selectedOptions.includes(option.key)">
            <label>
              <input 
                type="checkbox" 
                [value]="option.key"
                [checked]="selectedOptions.includes(option.key)"
                (change)="toggleOption(option.key)"
                [disabled]="submitted">
              <span class="option-key">{{ option.key }}.</span>
              <span class="option-text">
                <app-markdown-renderer [content]="option.value"></app-markdown-renderer>
              </span>
            </label>
          </div>
        </div>
      </div>

      <!-- 判断题 -->
      <div *ngIf="question.type === 'TRUE_FALSE'" class="options-section">
        <h3>请选择:</h3>
        <div class="options">
          <div class="option-item" [class.selected]="selectedOptions.includes('true')">
            <label>
              <input 
                type="radio" 
                name="trueFalse" 
                value="true"
                [checked]="selectedOptions.includes('true')"
                (change)="toggleOption('true')"
                [disabled]="submitted">
              <span class="option-text">正确</span>
            </label>
          </div>
          <div class="option-item" [class.selected]="selectedOptions.includes('false')">
            <label>
              <input 
                type="radio" 
                name="trueFalse" 
                value="false"
                [checked]="selectedOptions.includes('false')"
                (change)="toggleOption('false')"
                [disabled]="submitted">
              <span class="option-text">错误</span>
            </label>
          </div>
        </div>
      </div>

      <!-- 填空题 / 简答题 / 概述题 -->
      <div *ngIf="question.type === 'FILL_BLANK' || question.type === 'SHORT_ANSWER' || question.type === 'ESSAY'" class="answer-section">
        <h3>你的答案:</h3>
        <textarea 
          [(ngModel)]="userAnswer" 
          [disabled]="submitted"
          [placeholder]="question.type === 'ESSAY' ? '请输入你的详细回答...' : '请输入你的答案...'"
          [rows]="question.type === 'ESSAY' ? 10 : 3"></textarea>
      </div>

      <!-- 已选答案提示 (选择题) -->
      <div *ngIf="isChoiceQuestion() && selectedOptions.length > 0 && !submitted" 
           class="selected-answer-hint"
           role="status"
           aria-live="polite"
           aria-label="已选答案">
        <p><strong>你的选择:</strong> 
          <span class="selected-options">{{ selectedOptions.join(', ') }}</span>
        </p>
      </div>

      <div class="action-buttons" *ngIf="!submitted && user">
        <button class="btn btn-primary" 
                (click)="submitAnswer()" 
                [disabled]="isChoiceQuestion() && selectedOptions.length === 0"
                [attr.aria-label]="selectedOptions.length === 0 ? '请先选择答案' : '提交答案'">
          提交答案
        </button>
      </div>

      <div *ngIf="submitted" class="result-section">
        <div [class]="isCorrect ? 'result-correct' : 'result-incorrect'">
          <h3>{{ isCorrect ? '✓ 回答正确!' : '✗ 回答错误' }}</h3>
          <p>得分: {{ score }}</p>
        </div>

        <div class="correct-answer">
          <h3>正确答案:</h3>
          <app-markdown-renderer [content]="question.answer"></app-markdown-renderer>
        </div>

        <div *ngIf="question.explanation" class="explanation">
          <h3>答案解析:</h3>
          <app-markdown-renderer [content]="question.explanation"></app-markdown-renderer>
        </div>

        <div *ngIf="question.aiExplanation" class="ai-explanation">
          <h3>AI讲解:</h3>
          <app-markdown-renderer [content]="question.aiExplanation"></app-markdown-renderer>
        </div>
      </div>

      <div *ngIf="!user" class="login-prompt">
        <p>请先登录后再答题</p>
      </div>
    </div>
  </div>
</div>

// frontend/src/pages/QuestionDetail.tsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { questionAPI, answerAPI, collectionAPI } from '../api';
import type { Question } from '../api';
import { useAuth } from '../AuthContext';

const QuestionDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const [question, setQuestion] = useState<Question | null>(null);
  const [answer, setAnswer] = useState('');
  const [result, setResult] = useState<any>(null);
  const [isCollected, setIsCollected] = useState(false);
  const [loading, setLoading] = useState(true);
  const { user } = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    loadQuestion();
    if (user && id) {
      checkCollection();
    }
  }, [id, user]);

  const loadQuestion = async () => {
    try {
      setLoading(true);
      const response = await questionAPI.getById(Number(id));
      if (response.data.success) {
        setQuestion(response.data.data);
      }
    } catch (error) {
      console.error('Failed to load question:', error);
    } finally {
      setLoading(false);
    }
  };

  const checkCollection = async () => {
    try {
      const response = await collectionAPI.isCollected(user!.id, Number(id));
      if (response.data.success) {
        setIsCollected(response.data.data);
      }
    } catch (error) {
      console.error('Failed to check collection:', error);
    }
  };

  const handleSubmit = async () => {
    if (!user) {
      alert('请先登录');
      navigate('/login');
      return;
    }

    try {
      const response = await answerAPI.submit(
        { questionId: Number(id), answer },
        user.id
      );
      if (response.data.success) {
        setResult(response.data.data);
        alert(`提交成功！${response.data.data.isCorrect ? '答案正确！' : '答案错误'} 得分: ${response.data.data.score}`);
      }
    } catch (error) {
      console.error('Failed to submit answer:', error);
      alert('提交失败');
    }
  };

  const handleCollection = async () => {
    if (!user) {
      alert('请先登录');
      navigate('/login');
      return;
    }

    try {
      if (isCollected) {
        // 取消收藏逻辑需要先获取collection id
        alert('取消收藏功能需要完善');
      } else {
        const response = await collectionAPI.add(Number(id), undefined, user.id);
        if (response.data.success) {
          setIsCollected(true);
          alert('收藏成功');
        }
      }
    } catch (error: any) {
      alert(error.response?.data?.message || '操作失败');
    }
  };

  if (loading) return <div style={{ padding: '20px' }}>加载中...</div>;
  if (!question) return <div style={{ padding: '20px' }}>题目不存在</div>;

  const getQuestionTypeLabel = (type: string) => {
    const types: Record<string, string> = {
      SINGLE_CHOICE: '单选题',
      MULTIPLE_CHOICE: '多选题',
      TRUE_FALSE: '判断题',
      FILL_BLANK: '填空题',
      SHORT_ANSWER: '简答题',
      ESSAY: '概述题',
    };
    return types[type] || type;
  };

  const renderOptions = () => {
    if (!question.options) return null;
    
    try {
      const options = JSON.parse(question.options);
      return (
        <div style={{ marginTop: '15px' }}>
          <h4>选项:</h4>
          {Array.isArray(options) ? (
            options.map((option: any, index: number) => (
              <div key={index} style={{ padding: '8px', marginBottom: '5px', background: '#f5f5f5', borderRadius: '4px' }}>
                {typeof option === 'string' ? option : `${option.key}. ${option.value}`}
              </div>
            ))
          ) : (
            Object.entries(options).map(([key, value]) => (
              <div key={key} style={{ padding: '8px', marginBottom: '5px', background: '#f5f5f5', borderRadius: '4px' }}>
                {key}. {String(value)}
              </div>
            ))
          )}
        </div>
      );
    } catch (e) {
      return <div style={{ marginTop: '15px' }}><p>选项: {question.options}</p></div>;
    }
  };

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '20px' }}>
      <button onClick={() => navigate(-1)} style={{ marginBottom: '20px', padding: '8px 16px', cursor: 'pointer' }}>
        ← 返回
      </button>

      <div style={{ padding: '20px', border: '1px solid #ddd', borderRadius: '8px', background: '#fff' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start', marginBottom: '15px' }}>
          <h2 style={{ margin: 0 }}>{question.title}</h2>
          <button 
            onClick={handleCollection}
            style={{ 
              padding: '8px 16px', 
              cursor: 'pointer', 
              background: isCollected ? '#ffc107' : '#28a745',
              color: 'white',
              border: 'none',
              borderRadius: '5px'
            }}
          >
            {isCollected ? '已收藏' : '收藏'}
          </button>
        </div>

        <div style={{ marginBottom: '10px', display: 'flex', gap: '10px' }}>
          <span style={{ padding: '4px 12px', background: '#e3f2fd', color: '#1976d2', borderRadius: '4px' }}>
            {getQuestionTypeLabel(question.type)}
          </span>
          <span style={{ padding: '4px 12px', background: '#f3e5f5', color: '#7b1fa2', borderRadius: '4px' }}>
            难度: {question.difficulty}
          </span>
        </div>

        <div style={{ marginTop: '20px', marginBottom: '20px' }}>
          <h3>题目内容:</h3>
          <p style={{ fontSize: '16px', lineHeight: '1.6' }}>{question.content}</p>
        </div>

        {renderOptions()}

        {question.tags && (
          <div style={{ marginTop: '15px' }}>
            <strong>标签: </strong>
            {question.tags.split(',').map((tag, index) => (
              <span key={index} style={{ marginLeft: '5px', padding: '2px 8px', background: '#e0e0e0', borderRadius: '3px', fontSize: '12px' }}>
                {tag}
              </span>
            ))}
          </div>
        )}

        <div style={{ marginTop: '30px', padding: '20px', background: '#f9f9f9', borderRadius: '8px' }}>
          <h3>提交答案</h3>
          <textarea
            value={answer}
            onChange={(e) => setAnswer(e.target.value)}
            placeholder="请输入你的答案..."
            style={{ width: '100%', minHeight: '100px', padding: '10px', fontSize: '14px', border: '1px solid #ddd', borderRadius: '5px' }}
          />
          <button 
            onClick={handleSubmit}
            style={{ marginTop: '10px', padding: '10px 20px', cursor: 'pointer', background: '#007bff', color: 'white', border: 'none', borderRadius: '5px' }}
          >
            提交答案
          </button>
        </div>

        {result && (
          <div style={{ marginTop: '20px', padding: '15px', background: result.isCorrect ? '#d4edda' : '#f8d7da', borderRadius: '8px' }}>
            <h4>{result.isCorrect ? '✓ 回答正确！' : '✗ 回答错误'}</h4>
            <p>得分: {result.score}</p>
            {question.explanation && (
              <div>
                <h4>答案解析:</h4>
                <p>{question.explanation}</p>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default QuestionDetail;
