// frontend/src/app/pages/register.component.ts
import { Component } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { ApiService } from '../services/api.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  username = '';
  password = '';
  email = '';
  fullName = '';
  error = '';
  success = '';

  constructor(
    private apiService: ApiService,
    private router: Router
  ) {}

  handleSubmit(): void {
    this.error = '';
    this.success = '';

    this.apiService.register({
      username: this.username,
      password: this.password,
      email: this.email,
      fullName: this.fullName
    }).subscribe({
      next: (response) => {
        if (response.success) {
          this.success = '注册成功！正在跳转到登录页面...';
          setTimeout(() => this.router.navigate(['/login']), 2000);
        } else {
          this.error = response.message;
        }
      },
      error: (err) => {
        this.error = err.error?.message || '注册失败，请重试';
      }
    });
  }
}

<div style="max-width: 400px; margin: 50px auto; padding: 20px;">
  <h2>注册</h2>
  <div *ngIf="error" style="color: red; margin-bottom: 10px;">{{ error }}</div>
  <div *ngIf="success" style="color: green; margin-bottom: 10px;">{{ success }}</div>
  <form (ngSubmit)="handleSubmit()">
    <div style="margin-bottom: 15px;">
      <label>用户名:</label>
      <input
        type="text"
        [(ngModel)]="username"
        name="username"
        required
        style="width: 100%; padding: 8px; margin-top: 5px;"
      />
    </div>
    <div style="margin-bottom: 15px;">
      <label>邮箱:</label>
      <input
        type="email"
        [(ngModel)]="email"
        name="email"
        required
        style="width: 100%; padding: 8px; margin-top: 5px;"
      />
    </div>
    <div style="margin-bottom: 15px;">
      <label>姓名:</label>
      <input
        type="text"
        [(ngModel)]="fullName"
        name="fullName"
        style="width: 100%; padding: 8px; margin-top: 5px;"
      />
    </div>
    <div style="margin-bottom: 15px;">
      <label>密码:</label>
      <input
        type="password"
        [(ngModel)]="password"
        name="password"
        required
        style="width: 100%; padding: 8px; margin-top: 5px;"
      />
    </div>
    <button type="submit" style="padding: 10px 20px; cursor: pointer;">
      注册
    </button>
    <div style="margin-top: 15px;">
      已有账号？<a routerLink="/login">登录</a>
    </div>
  </form>
</div>

// frontend/src/pages/Register.tsx
import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { authAPI } from '../api';

const Register: React.FC = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [email, setEmail] = useState('');
  const [fullName, setFullName] = useState('');
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccess('');

    try {
      const response = await authAPI.register({ username, password, email, fullName });
      if (response.data.success) {
        setSuccess('注册成功！正在跳转到登录页面...');
        setTimeout(() => navigate('/login'), 2000);
      } else {
        setError(response.data.message);
      }
    } catch (err: any) {
      setError(err.response?.data?.message || '注册失败，请重试');
    }
  };

  return (
    <div style={{ maxWidth: '400px', margin: '50px auto', padding: '20px' }}>
      <h2>注册</h2>
      {error && <div style={{ color: 'red', marginBottom: '10px' }}>{error}</div>}
      {success && <div style={{ color: 'green', marginBottom: '10px' }}>{success}</div>}
      <form onSubmit={handleSubmit}>
        <div style={{ marginBottom: '15px' }}>
          <label>用户名:</label>
          <input
            type="text"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            required
            style={{ width: '100%', padding: '8px', marginTop: '5px' }}
          />
        </div>
        <div style={{ marginBottom: '15px' }}>
          <label>邮箱:</label>
          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
            style={{ width: '100%', padding: '8px', marginTop: '5px' }}
          />
        </div>
        <div style={{ marginBottom: '15px' }}>
          <label>姓名:</label>
          <input
            type="text"
            value={fullName}
            onChange={(e) => setFullName(e.target.value)}
            style={{ width: '100%', padding: '8px', marginTop: '5px' }}
          />
        </div>
        <div style={{ marginBottom: '15px' }}>
          <label>密码:</label>
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            style={{ width: '100%', padding: '8px', marginTop: '5px' }}
          />
        </div>
        <button type="submit" style={{ padding: '10px 20px', cursor: 'pointer' }}>
          注册
        </button>
        <div style={{ marginTop: '15px' }}>
          已有账号？<Link to="/login">登录</Link>
        </div>
      </form>
    </div>
  );
};

export default Register;
